/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';

/* PATIENTS APP*/
export const PATIENTS_GET_LIST = "PATIENTS_GET_LIST";
export const PATIENTS_GET_LIST_SUCCESS = "PATIENTS_GET_LIST_SUCCESS";
export const PATIENTS_GET_LIST_ERROR = "PATIENTS_GET_LIST_ERROR";
export const PATIENTS_GET_LIST_WITH_FILTER = "PATIENTS_GET_LIST_WITH_FILTER";
export const PATIENTS_GET_LIST_WITH_ORDER = "PATIENTS_GET_LIST_WITH_ORDER";
export const PATIENTS_GET_LIST_SEARCH = "PATIENTS_GET_LIST_SEARCH";
export const PATIENTS_ADD_ITEM = "PATIENTS_ADD_ITEM";
export const PATIENTS_ADD_ITEM_SUCCESS = "PATIENTS_ADD_ITEM_SUCCESS";
export const PATIENTS_ADD_ITEM_ERROR = "PATIENTS_ADD_ITEM_ERROR";
export const PATIENTS_REMOVE_ITEM = "PATIENTS_REMOVE_ITEM";
export const PATIENTS_REMOVE_ITEM_SUCCESS = "PATIENTS_REMOVE_ITEM_SUCCESS";
export const PATIENTS_REMOVE_ITEM_ERROR = "PATIENTS_REMOVE_ITEM_ERROR";
export const PATIENTS_SELECTED_ITEMS_CHANGE = "PATIENTS_SELECTED_ITEMS_CHANGE";
export const PATIENTS_DISCHARGE_ITEM = "PATIENTS_DISCHARGE_ITEM";
export const PATIENTS_DISCHARGE_ITEM_SUCCESS = "PATIENTS_DISCHARGE_ITEM_SUCCESS";
export const PATIENTS_DISCHARGE_ITEM_ERROR = "PATIENTS_DISCHARGE_ITEM_ERROR";
export const PATIENTS_DISCHARGED_REMOVE_ITEM = "PATIENTS_DISCHARGED_REMOVE_ITEM";
export const PATIENTS_DISCHARGED_REMOVE_ITEM_SUCCESS = "PATIENTS_DISCHARGED_REMOVE_ITEM_SUCCESS";
export const PATIENTS_DISCHARGED_REMOVE_ITEM_ERROR = "PATIENTS_DISCHARGED_REMOVE_ITEM_ERROR";
export const PATIENTS_GET_LIST_DISCHARGED = "PATIENTS_GET_LIST_DISCHARGED";
export const PATIENTS_GET_LIST_DISCHARGED_SUCCESS = "PATIENTS_GET_LIST_DISCHARGED_SUCCESS";
export const PATIENTS_GET_LIST_DISCHARGED_ERROR = "PATIENTS_GET_LIST_DISCHARGED_ERROR";
export const PATIENTS_GET_LIST_ALL = "PATIENTS_GET_LIST_ALL";
export const PATIENTS_GET_LIST_ALL_SUCCESS = "PATIENTS_GET_LIST_ALL_SUCCESS";
export const PATIENTS_GET_LIST_ALL_ERROR = "PATIENTS_GET_LIST_ALL_ERROR";
export const PATIENTS_ADMIT_ITEM = "PATIENTS_ADMIT_ITEM";
export const PATIENTS_ADMIT_ITEM_SUCCESS = "PATIENTS_ADMIT_ITEM_SUCCESS";
export const PATIENTS_ADMIT_ITEM_ERROR = "PATIENTS_ADMIT_ITEM_ERROR";

/* SURVEY DETAIL APP*/
export const SURVEY_GET_DETAILS = "SURVEY_GET_DETAILS";
export const SURVEY_GET_DETAILS_SUCCESS = "SURVEY_GET_DETAILS_SUCCESS";
export const SURVEY_GET_DETAILS_ERROR = "SURVEY_GET_DETAILS_ERROR";
export const SURVEY_DELETE_QUESTION = "SURVEY_DELETE_QUESTION";
export const SURVEY_SAVE = "SURVEY_SAVE";

/* WARDS APP */
export const WARDS_GET_LIST = "WARDS_GET_LIST";
export const WARDS_GET_LIST_SUCCESS = "WARDS_GET_LIST_SUCCESS";
export const WARDS_GET_LIST_ERROR = "WARDS_GET_LIST_ERROR";
